rpc_url: https://api.devnet.solana.com
transfers:
  - secret_key: <your_private_key_here>
    to: <money_reciever_address>
    amount: 1000 # lamports
  - secret_key: <your_private_key_here>
    to: <money_reciever_address>
    amount: 2000
  - secret_key: <your_private_key_here>
    to: <money_reciever_address>
    amount: 3000
  - secret_key: <your_private_key_here>
    to: <money_reciever_address>
    amount: 4000
