rpc_url: https://api.mainnet-beta.solana.com
wallets:
  - MJKqp326RZCHnAAbew9MDdui3iCKWco7fsK9sVuZTX2
  - 22sUvkaWf5FdXKj4183ZzVMjSizVSWiXn4LhPtxMbfnV
  - C4Qi3k63JrKk4YgjQxvhEZz32pC4kU9GoogdtkefX7sN
  - 8oF8Fpiac72HZQCJmAGAZvJUsQtHLmSH9BRhQgiZ79JB
  - Ng8yFkgxrnajY4b4R9XGpgUviXaGD4J39yGJ3BCSmvV
  - 7Dg5QMDNUkyj5cGN85Mc6dTmPf6t9C4mUAufoSLP7eFz
  - 4cw2tSz8uaTqPfgQSikRG2bgSes6piPVd6NR7XqSyjYh
  - C9qLjX5mFtXwCkgdUtNMzBcNZkEp7F4FC2AZTzwbXHmi
  - 5ugh3Wsrq1Z7wto64xVCzANxbuk6f9H6JKwCL62NA7Ay
  - D1nAMbQMg2YGh5T1wDkh3Q3hphuaFFDo4zyKrTFkiXhi
  - WA6YaufXeca5aj17jYgV7BuRBwJTWDYcyjDqYSiBc3y
  - A31jE6TiyNv5XyQUmZNTcqaVha2ExA73WqAKjgGpnC5i
  - gpoo1atPkrKnfxQ4Qt214ErbgBBJeiksL1EjqBHynbo
